export const APP_SHORTCUTS = {
    CLOSE_OVERLAYS: { id: 'sys.close_overlays', combo: 'escape', description: 'Close/Cancel All Overlays', category: 'System' },
    OPEN_PALETTE_CTRL: { id: 'sys.open_palette_ctrl', combo: 'ctrl+k', description: 'Open Command Palette', category: 'System' },
    OPEN_PALETTE_SLASH: { id: 'sys.open_palette_slash', combo: '/', description: 'Open Command Palette', category: 'System' },
    UNDO: { id: 'edit.undo', combo: 'ctrl+z', description: 'Undo', category: 'Editing' },
    REDO: { id: 'edit.redo', combo: 'ctrl+y', description: 'Redo', category: 'Editing' },
    ROLLBACK_LAST: { id: 'edit.rollback_last', combo: 'ctrl+shift+z', description: 'Rollback Last Operation', category: 'Editing' },
    CYCLE_KEYMAP_MODE: { id: 'sys.cycle_keymap', combo: 'ctrl+shift+m', description: 'Cycle Keymap Mode', category: 'System' },
    TOGGLE_ZEN: { id: 'flow.toggle_zen', combo: 'alt+z', description: 'Toggle Zen Mode', category: 'Flow' },
    QUICK_CAPTURE: { id: 'flow.quick_capture', combo: 'ctrl+shift+a', description: 'Quick Capture', category: 'Flow' },
    JUMP_NEXT_PENDING: { id: 'flow.jump_pending', combo: 'ctrl+j', description: 'Jump to Next Pending', category: 'Flow' },
    FOCUS_SIDEBAR_FILTER: { id: 'nav.focus_sidebar_filter', combo: 'ctrl+shift+f', description: 'Focus Sidebar Filter', category: 'Navigation' },
    VIEW_TODAY: { id: 'nav.view_today', combo: 'alt+1', description: 'View: Today', category: 'Navigation' },
    VIEW_ACTIVE: { id: 'nav.view_active', combo: 'alt+2', description: 'View: Active', category: 'Navigation' },
    VIEW_ARCHIVED: { id: 'nav.view_archived', combo: 'alt+3', description: 'View: Archived', category: 'Navigation' },
    VIEW_DUE_WEEK: { id: 'nav.view_due_week', combo: 'alt+4', description: 'View: Due Week', category: 'Navigation' },
    VIEW_REFERENCE: { id: 'nav.view_reference', combo: 'alt+5', description: 'View: Reference', category: 'Navigation' },
    VIEW_QUICK_INBOX: { id: 'nav.view_quick_inbox', combo: 'alt+6', description: 'View: Quick Inbox', category: 'Navigation' },
    MACRO_OVERDUE_SWEEP: { id: 'flow.macro_overdue', combo: 'alt+shift+1', description: 'Macro: Today Overdue Sweep', category: 'Flow' },
    MACRO_CAPTURE_INBOX: { id: 'flow.macro_capture', combo: 'alt+shift+2', description: 'Macro: Capture + Inbox', category: 'Flow' },
    MACRO_WEEKLY_PLANNING: { id: 'flow.macro_weekly', combo: 'alt+shift+3', description: 'Macro: Weekly Planning', category: 'Flow' },
    ADD_BOOKMARK: { id: 'nav.add_bookmark', combo: 'alt+b', description: 'Add Bookmark for Current Path', category: 'Navigation' },
    ADD_ITEM_TO_TOPIC: { id: 'edit.add_item_to_topic', combo: 'ctrl+enter', description: 'Add Item to Topic', category: 'Editing' },
    MOVE_ITEM_UP: { id: 'edit.move_item_up', combo: 'ctrl+shift+arrowup', description: 'Move Item Up', category: 'Editing' },
    MOVE_ITEM_DOWN: { id: 'edit.move_item_down', combo: 'ctrl+shift+arrowdown', description: 'Move Item Down', category: 'Editing' }
};
